
Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-12.04"

  config.vm.define :web do |web|
    web.vm.forward_port 80, 8080
    web.vm.forward_port 22, 2222
    web.vm.provision :chef_solo do |chef|
      chef.add_recipe 'apt'
      chef.add_recipe 'build-essential'
      chef.add_recipe 'git'
      chef.add_recipe 'python'
      chef.add_recipe 'apache2'
      chef.add_recipe 'apache2::mod_wsgi'
      chef.add_recipe 'postgresql::server'
      chef.add_recipe 'nodejs'
      chef.add_recipe 'django'
      chef.add_recipe 'django::postgres'
      chef.json = {
        :postgresql => {
          :password => {
            "postgres" => "testing",
          },
          :databases => [{
            "owner" => "postgres",
            "name" => "production_djeverything",
          }],
        },
      }

    end

  end

end